# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28ab944719131e3ddece6349af54c13fcd0e67d6835c4aa132df94e3c9c25f09bceb7fc4d9b581f625a06bd1cc3e9f78fa92d7e3a63abcaea8edb377804b822e

test:
  secret_key_base: 7bc3c2f5db228fa72ed155a53968769e4a0d7fe7be30b46b8ae580e9fa816707f6024132408b01164b4f2ab34838d0502ee641e5ad2daac237fddf8a8dd88df2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
